### ISSUE TITLE
nextjs13

### ISSUE THREAD

**Issue by alu0101056944** [ULL-MII-SYTWS-2324/nextjs13-marcos-barrios-lorenzo-alu0101056944#1]

**Comment by alu0101056944** [comment]
Terminé los informes de las ramas `lesson-1` a `lesson-12` (disponibles en el directorio docs/report.md de cada una) y también terminé el tutorial de la rama `learn-next-ai` cuyo informe está también en docs/report.md. El deploy de netlify está en [https://learn-next-ai--marvelous-ganache-642849.netlify.app/](https://learn-next-ai--marvelous-ganache-642849.netlify.app/), pero no puedo hacer deploy en vercel porque está pendiente la autorización del repositorio en la organización.

Otro problema más importante todavía es que no puedo probar la app de AI porque no dispongo de una llave de open AI.

@crguezl

**Comment by crguezl** [comment]
@alu0101056944 

¡Está estupendo el trabajo!. En cuanto al despliegue en Vercel no se puede hacer desde la organización sin que tenga que pagar.
Lo que yo hago es que hago un fork del repo a mi cuenta personal (en tu caso a `alu0101056944`) y desde ahí si que Vercel te permite hacer el despliegue gratis.

Felices fiestas
